version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
  gcp-gcr: circleci/gcp-gcr@0.13.0            
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: myContext
          image: my-image
          registry-url: us.gcr.io