version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
  gcp-gcr: circleci/gcp-gcr@0.13.0
  gcp-gke: circleci/gcp-gke@1.2.0            
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-image:
          dockerfile: "Dockerfile"
          image: eschool-fe
          registry-url: eu.gcr.io
          tag: ${CIRCLE_SHA1:0:7}
      # Push and tag docker image according to commit SHA1 hash 
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: eschool-fe
          registry-url: eu.gcr.io
          tag: ${CIRCLE_SHA1:0:7}
      # Tag pusshed image as latest
      - gcp-gcr/tag-image:
          image: eschool-fe
          registry-url: eu.gcr.io
          source-tag: ${CIRCLE_SHA1:0:7}
          target-tag: latest