executors:
  my-executor:
    docker:
      - image: 'my-org/circleci-python:3.7'
orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: myContext
          executor: my-executor
          image: my-image
          registry-url: us.gcr.io
          setup-remote-docker: true
          use-docker-layer-caching: true