version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
  gcp-gcr: circleci/gcp-gcr@0.13.0
  gcp-gke: circleci/gcp-gke@1.2.0            
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          tag: "latest"
          extra_build_args: "--build-arg BUILDMODE=$BUILDMODE"
          context: my-context1
          image: eschool-fe
          registry-url: eu.gcr.io
      # - gcp-gke/publish-and-rollout-image:
      #     cluster: gcp-testing
      #     context: my-context1
      #     container: eschool-fe
      #     deployment: demo
      #     image: eschool-fe
      #     tag: "latest"
      #     requires: 
      #       - gcp-gcr/build-and-push-image
